version: '3.8'

services:
  kics:
    build:
      context: ../../
      dockerfile: scripts/docker/images/Dockerfile.checkmarx
    volumes:
      - ${FOLDER_TO_EVALUATE_CODE}:/code:ro
      - ${FOLDER_TO_EVALUATE_CODE_RESULT}:/results
    working_dir: /code
    command: ["scan", "-p", "/code", "-o", "/results","--verbose"]
