version: '3.8'

# Definición de servicios
services:
  kics:
    # Construcción de la imagen
    build:
      # Directorio donde se encuentra el Dockerfile y el contexto de construcción
      context: ../../
      dockerfile: scripts/docker/images/Dockerfile.checkmarx
    
    # Volúmenes montados en el contenedor
    volumes:
      # Volumen para la carpeta de código a evaluar
      - ${FOLDER_TO_EVALUATE_CODE}:/code:ro
      # Volumen para almacenar los resultados del escaneo
      - ${FOLDER_TO_EVALUATE_CODE_RESULT}:/results
    
    # Directorio de trabajo dentro del contenedor
    working_dir: /code
    
    # Comando que se ejecutará al iniciar el contenedor
    command: ["scan", "-p", "/code", "-o", "/results", "--verbose"]

    # Configuración de red
    networks:
      - kics_network

# Definición de redes
networks:
  kics_network:
    driver: bridge
