# Utiliza la imagen base de Checkmarx KICS
FROM checkmarx/kics:latest

# Etiquetas opcionales para proporcionar metadatos sobre la imagen
LABEL maintainer="Jorge Reyes" \
      version="1.0" \
      description="Dockerfile para Checkmarx KICS para ejecutar escaneos de seguridad en Infraestructura como Código (IaC)."

# Establece el punto de entrada por defecto para el contenedor
# El punto de entrada es el comando que se ejecutará cuando se inicie el contenedor.
ENTRYPOINT ["kics"]